faq_data = {
    "What is Python?": "Python is a high-level programming language known for its simplicity and readability.",
    "What are the benefits of using Python?": "Python offers easy syntax, vast standard libraries, and community support.",
    "How do I install Python?": "You can download and install Python from the official website: https://www.python.org/downloads/",
    "What are the data types in Python?": "Python supports various data types including integers, floats, strings, lists, tuples, dictionaries, etc.",
    "What is a list in Python?": "A list is a collection of items in a particular order. Lists are mutable, meaning they can be changed after they are created.",
    "What is a dictionary in Python?": "A dictionary is a collection of key-value pairs. Each key is connected to a value, and you can use keys to access the values.",
    "What is a function in Python?": "A function is a block of code that runs when it is called. Functions allow you to reuse code and make programs more modular.",
    "How do I define a function in Python?": "You define a function using the `def` keyword, followed by the function name and parentheses.",
    "What is a loop in Python?": "A loop is used to execute a block of code repeatedly. Python has `for` and `while` loops.",
    "How do I write a for loop in Python?": "A `for` loop is written using the `for` keyword, followed by a variable name, the `in` keyword, and the sequence to loop through.",
    "How do I write a while loop in Python?": "A `while` loop is written using the `while` keyword, followed by a condition that evaluates to True or False.",
    "What is an if statement in Python?": "An `if` statement is used to test a condition and execute code based on whether the condition is true or false.",
    "How do I write an if statement in Python?": "An `if` statement is written using the `if` keyword, followed by a condition, and a colon.",
    "What are Python modules?": "Modules are files containing Python code that can be imported into other Python programs.",
    "How do I import a module in Python?": "You can import a module using the `import` keyword followed by the module name.",
    "What is an exception in Python?": "An exception is an error that occurs during the execution of a program. Python has a mechanism to catch and handle exceptions.",
    "How do I handle exceptions in Python?": "You handle exceptions using the `try` and `except` keywords.",
    "What is a class in Python?": "A class is a blueprint for creating objects. It defines a set of attributes and methods that the created objects will have.",
    "How do I define a class in Python?": "You define a class using the `class` keyword, followed by the class name and a colon.",
    "What is an object in Python?": "An object is an instance of a class. It is created using the class name followed by parentheses.",
    "What is inheritance in Python?": "Inheritance allows a class to inherit attributes and methods from another class.",
    "What is polymorphism in Python?": "Polymorphism allows methods to be used on different types of objects, enabling a single function to operate on different kinds of data.",
    "What is encapsulation in Python?": "Encapsulation is the bundling of data and methods that operate on that data within a single unit or class.",
    "How do I open a file in Python?": "You can open a file using the `open` function, which takes the file name and mode as arguments.",
    "What are the file modes in Python?": "File modes include 'r' for read, 'w' for write, 'a' for append, and 'b' for binary mode.",
    "How do I read a file in Python?": "You can read a file using the `read`, `readline`, or `readlines` methods of a file object.",
    "How do I write to a file in Python?": "You can write to a file using the `write` or `writelines` methods of a file object.",
    "What is a package in Python?": "A package is a way of structuring Python’s module namespace by using dotted module names.",
    "How do I create a package in Python?": "You create a package by creating a directory and adding an `__init__.py` file to it.",
    "What are lambda functions in Python?": "Lambda functions are small anonymous functions defined using the `lambda` keyword.",
    "How do I define a lambda function in Python?": "You define a lambda function using the `lambda` keyword, followed by parameters, a colon, and the expression.",
    "What is a decorator in Python?": "A decorator is a function that takes another function and extends its behavior without explicitly modifying it.",
    "How do I use a decorator in Python?": "You use a decorator by prefixing the function definition with the `@` symbol followed by the decorator function name.",
    "What are list comprehensions in Python?": "List comprehensions provide a concise way to create lists. They consist of brackets containing an expression followed by a `for` clause.",
    "How do I create a list comprehension in Python?": "You create a list comprehension using square brackets, followed by an expression and a `for` clause.",
    "What is a generator in Python?": "A generator is a function that returns an iterator and allows you to iterate over a sequence of values.",
    "How do I create a generator in Python?": "You create a generator using a function that contains one or more `yield` statements.",
    "What are iterators in Python?": "Iterators are objects that can be iterated upon, meaning they can return data, one element at a time.",
    "How do I create an iterator in Python?": "You create an iterator by implementing the `__iter__` and `__next__` methods in a class.",
    "What is a virtual environment in Python?": "A virtual environment is an isolated Python environment that allows you to manage dependencies for different projects separately.",
    "How do I create a virtual environment in Python?": "You create a virtual environment using the `python -m venv <env_name>` command.",
    "How do I activate a virtual environment in Python?": "You activate a virtual environment using the `source <env_name>/bin/activate` command on Unix or `.\<env_name>\Scripts\activate` on Windows.",
    "How do I install packages in Python?": "You install packages using the `pip install <package_name>` command.",
    "What is pip in Python?": "Pip is the package installer for Python, used to install and manage software packages written in Python.",
    "How do I update pip in Python?": "You update pip using the `pip install --upgrade pip` command.",
    "What are some popular Python libraries?": "Popular Python libraries include NumPy, pandas, Matplotlib, SciPy, scikit-learn, TensorFlow, and PyTorch.",
    "What is NumPy in Python?": "NumPy is a library for numerical computing with support for arrays, matrices, and many mathematical functions.",
    "What is pandas in Python?": "Pandas is a data manipulation and analysis library that provides data structures like Series and DataFrame.",
    "What is Matplotlib in Python?": "Matplotlib is a plotting library that allows you to create static, animated, and interactive visualizations in Python.",
    "What is scikit-learn in Python?": "Scikit-learn is a machine learning library that provides simple and efficient tools for data analysis and modeling.",
    "What is TensorFlow in Python?": "TensorFlow is an open-source library for numerical computation and machine learning developed by Google.",
    "What is PyTorch in Python?": "PyTorch is an open-source machine learning library based on the Torch library, primarily developed by Facebook's AI Research lab.",
    "What is Flask in Python?": "Flask is a micro web framework written in Python used for developing web applications.",
    "How do I create a Flask app in Python?": "You create a Flask app by importing the Flask class and creating an instance of it, then defining routes using the `@app.route` decorator.",
    "What is Django in Python?": "Django is a high-level web framework that encourages rapid development and clean, pragmatic design.",
    "How do I create a Django project in Python?": "You create a Django project using the `django-admin startproject <project_name>` command.",
    "What is REST API in Python?": "A REST API (Representational State Transfer Application Programming Interface) is a set of rules that allows different software applications to communicate with each other.",
    "How do I create a REST API in Python?": "You create a REST API in Python using frameworks like Flask or Django along with libraries like Flask-RESTful or Django REST framework.",
    "What is Web Scraping in Python?": "Web scraping is the process of extracting data from websites using automated scripts.",
    "How do I perform web scraping in Python?": "You perform web scraping in Python using libraries like BeautifulSoup, Scrapy, and Selenium.",
    "What is BeautifulSoup in Python?": "BeautifulSoup is a library used for parsing HTML and XML documents and extracting data from them.",
    "What is Selenium in Python?": "Selenium is a library used for automating web browser interaction, often used for web scraping and testing web applications.",
    "What is Jupyter Notebook?": "Jupyter Notebook is an open-source web application that allows you to create and share documents containing live code, equations, visualizations, and narrative text.",
    "How do I install Jupyter Notebook?": "You install Jupyter Notebook using the `pip install notebook` command.",
    "How do I start Jupyter Notebook?": "You start Jupyter Notebook using the `jupyter notebook` command in your terminal or command prompt.",
}
